### ISSUE TITLE
Unable to consume the latest released version

### ISSUE THREAD

**Issue by krmahadevan** [pecker-io/karate-grpc#22]
Following are the steps that I am following:

1. Create a new project using the command `mvn archetype:generate`
2. After the template project has been created I am basically updating the dependencies to 

```xml
<dependency>
  <groupId>com.github.thinkerou</groupId>
  <artifactId>karate-grpc-core</artifactId>
  <version>1.0.3</version>
  <scope>test</scope>		  
</dependency>
```

Now when I run `mvn dependency:resolve` I get the below error

```bash
[INFO] 
[INFO] ---------------< com.rationaleemotions:code_playground >----------------
[INFO] Building code_playground 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/github/thinkerou/karate-grpc-parent/1.0.3/karate-grpc-parent-1.0.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.pom
Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.pom (2.3 kB at 4.8 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.783 s
[INFO] Finished at: 2021-10-26T17:21:18+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project code_playground: Could not resolve dependencies for project com.rationaleemotions:code_playground:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.thinkerou:karate-grpc-core:jar:1.0.3: Failed to read artifact descriptor for com.github.thinkerou:karate-grpc-core:jar:1.0.3: Could not find artifact com.github.thinkerou:karate-grpc-parent:pom:1.0.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
```

It looks like there's something wrong with the publishing of the grpc-parent pom file.

I went back and checked https://repo1.maven.org/maven2/com/github/thinkerou/karate-grpc-parent/ and noticed that `1.0.3` does not exist there.

Would this need a new release to get this sorted out ? Or maybe just attempt a release for `1.0.3` karate-grpc-parent alone ? Basically re-run the release job, so that it passes for the parent-pom but fails for everything else since those versions are already there?

**Comment by thinkerou** [comment]
@krmahadevan I can not reproduce the issue.
please remove or update `~/.m2/settings.xml`, I run `mvn dependency:resolve` successful.
```
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for karate-grpc-parent 1.0.3:
[INFO]
[INFO] karate-grpc-parent ................................. SUCCESS [ 12.313 s]
[INFO] karate-grpc-core ................................... SUCCESS [ 14.541 s]
[INFO] karate-grpc-demo ................................... SUCCESS [ 16.984 s]
[INFO] karate-grpc-helper ................................. SUCCESS [  2.197 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.408 s
[INFO] Finished at: 2022-06-11T22:31:53+08:00
[INFO] ------------------------------------------------------------------------
```

```
➜  thinkerou pwd
/Users/thinerou/.m2/repository/com/github/thinkerou
➜  thinkerou ls
karate-grpc-core   karate-grpc-parent karate-grpc-proto
➜  thinkerou ls karate-grpc-parent/1.0.3
karate-grpc-parent-1.0.3.pom.lastUpdated
➜  thinkerou ls karate-grpc-core/1.0.3/
_remote.repositories            karate-grpc-core-1.0.3.jar.sha1 karate-grpc-core-1.0.3.pom.sha1
karate-grpc-core-1.0.3.jar      karate-grpc-core-1.0.3.pom
```

**Comment by thinkerou** [comment]
@krmahadevan please use `1.0.4`, thanks!

**Comment by chengxinxing-airwallex** [comment]
@thinkerou 
I use 1.0.4 in the grade dependencies: implementation("com.github.thinkerou:karate-grpc-core:1.0.4") , but could not resolve it.
Is karate-grpc only for maven?
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/50281891/173488673-e880d8b5-1c07-451b-9b33-a149377382ca.png">

**Comment by thinkerou** [comment]
> @thinkerou I use 1.0.4 in the grade dependencies: implementation("com.github.thinkerou:karate-grpc-core:1.0.4") , but could not resolve it. Is karate-grpc only for maven? <img alt="image" width="1129" src="https://user-images.githubusercontent.com/50281891/173488673-e880d8b5-1c07-451b-9b33-a149377382ca.png">

yes,
https://github.com/pecker-io/karate-grpc#gradle
need test, thanks!

**Comment by krmahadevan** [comment]
> @thinkerou I use 1.0.4 in the grade dependencies: implementation("com.github.thinkerou:karate-grpc-core:1.0.4") , but could not resolve it. Is karate-grpc only for maven? <img alt="image" width="1129" src="https://user-images.githubusercontent.com/50281891/173488673-e880d8b5-1c07-451b-9b33-a149377382ca.png">

It should work for Gradle and maven as well. I just now tried with https://mvnrepository.com/artifact/com.github.thinkerou/karate-grpc-core/1.0.4

and I am able to resolve the dependency.

Following is what I have as repository tag

```
repositories {
    mavenCentral()

    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
}

```

**Comment by krmahadevan** [comment]
@thinkerou - The issue is NOT resolved.

Here's the console output

```
[INFO] --------------------< org.example:testngBugProject >--------------------
[INFO] Building testngBugProject 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/github/thinkerou/karate-grpc-parent/1.0.4/karate-grpc-parent-1.0.4.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.635 s
[INFO] Finished at: 2022-06-14T10:14:55+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project testngBugProject: Could not resolve dependencies for project org.example:testngBugProject:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.github.thinkerou:karate-grpc-core:jar:1.0.4: Failed to read artifact descriptor for com.github.thinkerou:karate-grpc-core:jar:1.0.4: Could not find artifact com.github.thinkerou:karate-grpc-parent:pom:1.0.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

```

The [karate-grpc-core-1.0.4.pom file](https://repo1.maven.org/maven2/com/github/thinkerou/karate-grpc-core/1.0.4/karate-grpc-core-1.0.4.pom) has a parent pom dependency as below

```xml
<parent>
<artifactId>karate-grpc-parent</artifactId>
<groupId>com.github.thinkerou</groupId>
<version>1.0.4</version>
</parent>
```

and the parent pom file version `1.0.4` is not available https://repo1.maven.org/maven2/com/github/thinkerou/karate-grpc-parent/

**Comment by chengxinxing-airwallex** [comment]
while the version of karate-grpc-core is 1.0.4 (https://repo.maven.apache.org/maven2/com/github/thinkerou/karate-grpc-core/), the version of  karate-grpc-parent is 1.0.1 (https://repo.maven.apache.org/maven2/com/github/thinkerou/karate-grpc-parent/) 

If I use version 1.0.1, the gradle build successfully.

@thinkerou I think you need to publish karate-grpc-parent version 1.0.4

**Comment by thinkerou** [comment]
now only release `karate-grpc-core` 1.0.5 and `karate-grpc-parent` 1.0.5, please retry it.
`karate-grpc-demo` and `karate-grpc-helper` not release, thanks!

**Comment by krmahadevan** [comment]
@thinkerou 

Now this works fine

```
implementation 'com.github.thinkerou:karate-grpc-core:1.0.5'
```

Thanks for helping out. Closing this issue.

**Comment by ericdriggs** [comment]
Still getting a compile error using 
`implementation 'com.github.thinkerou:karate-grpc-core:1.0.5'`


`Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.thinkerou:karate-grpc-core:1.0.5.
     Required by:
         project :
      > Could not resolve com.github.thinkerou:karate-grpc-core:1.0.5.
         > Could not parse POM https://artifactory.prod.hulu.com/artifactory/hulu-mvn-releases/com/github/thinkerou/karate-grpc-core/1.0.5/karate-grpc-core-1.0.5.pom
            > Could not find com.github.thinkerou:karate-grpc-parent:${revision}.
      > Could not resolve com.github.thinkerou:karate-grpc-core:1.0.5.
         > Could not parse POM https://artifactory.prod.hulu.com/artifactory/Maven-Central/com/github/thinkerou/karate-grpc-core/1.0.5/karate-grpc-core-1.0.5.pom
            > Could not find com.github.thinkerou:karate-grpc-parent:${revision}.
      > Could not resolve com.github.thinkerou:karate-grpc-core:1.0.5.
         > Could not parse POM https://repo.maven.apache.org/maven2/com/github/thinkerou/karate-grpc-core/1.0.5/karate-grpc-core-1.0.5.pom
            > Could not find com.github.thinkerou:karate-grpc-parent:${revision}.

* `
