### ISSUE TITLE
Need to call grpc service with custom header as Metadata

### ISSUE THREAD

**Issue by sujitkirve** [pecker-io/karate-grpc#35]
Hi Team, 

Need to call grpc service with custom header (JWT token) as metadata along with request, so anyone know how can i pass it through karate?

**Comment by sujitkirve** [comment]
@thinkerou @ericdriggs  Can you please help here.

**Comment by kenil-fadia** [comment]
Hi @thinkerou any update on this one?

**Comment by thinkerou** [comment]
thanks everyone!
I have no time, sorry!
welcome commit pr, thanks!

**Comment by ericdriggs** [comment]
Recommend: https://github.com/fullstorydev/grpcurl

**Comment by kenil-fadia** [comment]
@sujitkirve @thinkerou  I have found a solution, i will create a PR for this soon

**Comment by pazaan** [comment]
Opened https://github.com/pecker-io/karate-grpc/pull/40 to address this.

**Comment by pazaan** [comment]
@thinkerou will you also do the 1.0.7 release for this so that it’s available to Maven?
