### ISSUE TITLE
Creation of the Public grpc client failing

### ISSUE THREAD

**Issue by YG007** [pecker-io/karate-grpc#7]
Hi @thinkerou  ,

I am trying to start run a dummy grpc client using the following command:
java -cp .:gson.jar:grpc-netty.jar:grpc-protobuf.jar:grpc-stub.jar:protobuf-java-util.jar:karate-grpc-core.jar:karate.jar: com.intuit.karate.netty.Main  `find . -name 'helloworld.feature'`

This includes the karate-grpc-core and its dependencies. This makes a call into the Java Interop but fails while the public client.

The grpc server is running on a privatye IP and the code snippet is attached for your reference:

Feature: grpc helloworld example
  Background:
    * def Client = Java.type('com.github.thinkerou.karate.GrpcClient')
    * def client = Client.create('10.223.4.142', 50051)
  Scenario: do it
       * def payload = read('requests/helloworld.json')
       * def response = client.call('helloworld.Greeter/SayHello', payload)
       * def response = JSON.parse(response)
       * print response
       * match response[0].message == 'Hello ALL'
       * def message = response[0].message

Can you help me out here?

**Comment by YG007** [comment]
Hi,

Can you look into the issue!

**Comment by thinkerou** [comment]
@YG007 according https://github.com/thinkerou/karate-grpc/blob/master/.travis.yml retry once, thanks! If it still have problem please ping me, thanks!

**Comment by YG007** [comment]
Hi @thinkerou ,

I saw the solution given but my problem seems to be different from the one described there. Can you have a look?

Thanks

**Comment by YG007** [comment]
Hey @thinkerou ,
Did you get the time to look into the solution?
Thanks

**Comment by thinkerou** [comment]
@YG007 ok，tonight.

**Comment by thinkerou** [comment]
why use the command:

> java -cp .:gson.jar:grpc-netty.jar:grpc-protobuf.jar:grpc-stub.jar:protobuf-java-util.jar:karate-grpc-core.jar:karate.jar: com.intuit.karate.netty.Main find . -name 'helloworld.feature'

**Comment by YG007** [comment]
I don't want to run the project through maven but only using jar files that are needed. Hence I was using the particular command .

**Comment by YG007** [comment]
Hi @thinkerou, Can you help me out here?
